/**
 * SearchPage — Full-Text Data Search (Advanced Mode only)
 *
 * Searches across all data entities: LGAs, alerts, forecasts, reports.
 * Phase 2: backend-powered search. Currently mock results.
 */
import GlassCard from "@/components/GlassCard";
import { Search, FileText, Map, Brain, Bell } from "lucide-react";
import { useState } from "react";

const MOCK_RESULTS = [
  { type: "lga", icon: Map, title: "Maiduguri", desc: "Risk score: 8.42 · 486K IDPs · IPC Phase 3+: 34.2%" },
  { type: "alert", icon: Bell, title: "Active Threat Alert — Maiduguri Metro", desc: "CRITICAL · 12 min ago · Inter-agency coordination in progress" },
  { type: "forecast", icon: Brain, title: "Bama LSTM Forecast (12-month)", desc: "Predicted events: 11.3 · Base risk: HIGH · Horizon: 12 months" },
  { type: "report", icon: FileText, title: "Weekly Situation Report — Wk 35", desc: "Generated by operations team · All regions · 6 KPIs included" },
];

export default function SearchPage() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<typeof MOCK_RESULTS>([]);

  const handleSearch = (q: string) => {
    setQuery(q);
    if (q.length > 1) {
      setResults(MOCK_RESULTS.filter((r) => r.title.toLowerCase().includes(q.toLowerCase()) || r.desc.toLowerCase().includes(q.toLowerCase())));
    } else {
      setResults([]);
    }
  };

  return (
    <div className="animate__animated animate__fadeInUp">
      <h1 className="text-xl font-extrabold text-dark-text mb-4 animate-fade-in">Search</h1>

      <GlassCard className="p-3 mb-6">
        <div className="flex items-center gap-3">
          <Search size={18} className="text-surface-500" />
          <input
            type="text"
            value={query}
            onChange={(e) => handleSearch(e.target.value)}
            placeholder="Search LGAs, alerts, forecasts, reports..."
            className="flex-1 bg-transparent text-sm text-dark-text placeholder:text-surface-500/50 focus:outline-none"
            autoFocus
          />
        </div>
      </GlassCard>

      {query.length > 1 && results.length === 0 && (
        <p className="text-sm text-surface-500 text-center py-8">No results for "{query}"</p>
      )}

      <div className="space-y-2">
        {results.map((r, i) => {
          const Icon = r.icon;
          return (
            <GlassCard key={i} className="p-4" hover>
              <div className="flex items-start gap-3">
                <Icon size={16} className="text-un-blue mt-0.5" />
                <div>
                  <h3 className="text-sm font-bold text-dark-text">{r.title}</h3>
                  <p className="text-[0.75rem] text-surface-400 mt-0.5">{r.desc}</p>
                </div>
              </div>
            </GlassCard>
          );
        })}
      </div>
    </div>
  );
}
